version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    ports:
      - 80:80
    depends_on:
      - violet

  violet:
    depends_on:
      - db
    build: .
    image:  violet:latest
    restart: always
    environment:
      DB_HOST: db
    command:  bash -c "./boot.sh run"
  db:
    image: mysql:5.7
    volumes:
      - /data/mysql/violet/data:/var/lib/mysql
    restart: always
    environment:
    # note: this should use env_file env/mysql.env and add env to .gitignore
      MYSQL_ROOT_PASSWORD: newpass
      MYSQL_DATABASE: violet
#    env_file:
#      - env/mysql.env